
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
  
    runs-on: ubuntu-latest

    #download repo
    steps:
    - uses: actions/checkout@v3
    
      #setup java
    - name: Set up JDK 11
      with:
        java-version: '11'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0
 
    - name: Setup gradlew
      run:  chmod +x gradlew

    - name: Execute Test
      run: ./gradlew cucumber    
      
   
